/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as ContentRouteImport } from './routes/content'
import { Route as CsamRouteImport } from './routes/csam'
import { Route as FlagsRouteImport } from './routes/flags'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as NamespacesRouteImport } from './routes/namespaces'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as TombstoneRouteImport } from './routes/tombstone'
import { Route as UsersRouteImport } from './routes/users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentRoute = ContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => rootRouteImport,
} as any)
const CsamRoute = CsamRouteImport.update({
  id: '/csam',
  path: '/csam',
  getParentRoute: () => rootRouteImport,
} as any)
const FlagsRoute = FlagsRouteImport.update({
  id: '/flags',
  path: '/flags',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const NamespacesRoute = NamespacesRouteImport.update({
  id: '/namespaces',
  path: '/namespaces',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const TombstoneRoute = TombstoneRouteImport.update({
  id: '/tombstone',
  path: '/tombstone',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/audit': typeof AuditRoute
  '/content': typeof ContentRoute
  '/csam': typeof CsamRoute
  '/flags': typeof FlagsRoute
  '/jobs': typeof JobsRoute
  '/legal': typeof LegalRoute
  '/namespaces': typeof NamespacesRoute
  '/reports': typeof ReportsRoute
  '/staff': typeof StaffRoute
  '/tombstone': typeof TombstoneRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/audit': typeof AuditRoute
  '/content': typeof ContentRoute
  '/csam': typeof CsamRoute
  '/flags': typeof FlagsRoute
  '/jobs': typeof JobsRoute
  '/legal': typeof LegalRoute
  '/namespaces': typeof NamespacesRoute
  '/reports': typeof ReportsRoute
  '/staff': typeof StaffRoute
  '/tombstone': typeof TombstoneRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/approvals': typeof ApprovalsRoute
  '/audit': typeof AuditRoute
  '/content': typeof ContentRoute
  '/csam': typeof CsamRoute
  '/flags': typeof FlagsRoute
  '/jobs': typeof JobsRoute
  '/legal': typeof LegalRoute
  '/namespaces': typeof NamespacesRoute
  '/reports': typeof ReportsRoute
  '/staff': typeof StaffRoute
  '/tombstone': typeof TombstoneRoute
  '/users': typeof UsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/approvals'
    | '/audit'
    | '/content'
    | '/csam'
    | '/flags'
    | '/jobs'
    | '/legal'
    | '/namespaces'
    | '/reports'
    | '/staff'
    | '/tombstone'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/approvals'
    | '/audit'
    | '/content'
    | '/csam'
    | '/flags'
    | '/jobs'
    | '/legal'
    | '/namespaces'
    | '/reports'
    | '/staff'
    | '/tombstone'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/approvals'
    | '/audit'
    | '/content'
    | '/csam'
    | '/flags'
    | '/jobs'
    | '/legal'
    | '/namespaces'
    | '/reports'
    | '/staff'
    | '/tombstone'
    | '/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApprovalsRoute: typeof ApprovalsRoute
  AuditRoute: typeof AuditRoute
  ContentRoute: typeof ContentRoute
  CsamRoute: typeof CsamRoute
  FlagsRoute: typeof FlagsRoute
  JobsRoute: typeof JobsRoute
  LegalRoute: typeof LegalRoute
  NamespacesRoute: typeof NamespacesRoute
  ReportsRoute: typeof ReportsRoute
  StaffRoute: typeof StaffRoute
  TombstoneRoute: typeof TombstoneRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content': {
      id: '/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof ContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/csam': {
      id: '/csam'
      path: '/csam'
      fullPath: '/csam'
      preLoaderRoute: typeof CsamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flags': {
      id: '/flags'
      path: '/flags'
      fullPath: '/flags'
      preLoaderRoute: typeof FlagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/namespaces': {
      id: '/namespaces'
      path: '/namespaces'
      fullPath: '/namespaces'
      preLoaderRoute: typeof NamespacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tombstone': {
      id: '/tombstone'
      path: '/tombstone'
      fullPath: '/tombstone'
      preLoaderRoute: typeof TombstoneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApprovalsRoute: ApprovalsRoute,
  AuditRoute: AuditRoute,
  ContentRoute: ContentRoute,
  CsamRoute: CsamRoute,
  FlagsRoute: FlagsRoute,
  JobsRoute: JobsRoute,
  LegalRoute: LegalRoute,
  NamespacesRoute: NamespacesRoute,
  ReportsRoute: ReportsRoute,
  StaffRoute: StaffRoute,
  TombstoneRoute: TombstoneRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
