/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as MeRouteImport } from './routes/me'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as CreateIndexRouteImport } from './routes/create.index'
import { Route as CreateImportRouteImport } from './routes/create.import'
import { Route as GuestVerifyRouteImport } from './routes/guest.verify'
import { Route as PlaygroundIndexRouteImport } from './routes/playground.index'
import { Route as PlaygroundDiffRouteImport } from './routes/playground.diff'
import { Route as CNsNameRouteImport } from './routes/c.$ns.$name'
import { Route as CNsNameEditRouteImport } from './routes/c.$ns.$name_.edit'
import { Route as CNsNameContributionsIndexRouteImport } from './routes/c.$ns.$name_.contributions.index'
import { Route as CNsNameContributionsNumberRouteImport } from './routes/c.$ns.$name_.contributions.$number'
import { Route as CNsNameContributionsNewRouteImport } from './routes/c.$ns.$name_.contributions.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateIndexRoute = CreateIndexRouteImport.update({
  id: '/create/',
  path: '/create/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateImportRoute = CreateImportRouteImport.update({
  id: '/create/import',
  path: '/create/import',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestVerifyRoute = GuestVerifyRouteImport.update({
  id: '/guest/verify',
  path: '/guest/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundIndexRoute = PlaygroundIndexRouteImport.update({
  id: '/playground/',
  path: '/playground/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundDiffRoute = PlaygroundDiffRouteImport.update({
  id: '/playground/diff',
  path: '/playground/diff',
  getParentRoute: () => rootRouteImport,
} as any)
const CNsNameRoute = CNsNameRouteImport.update({
  id: '/c/$ns/$name',
  path: '/c/$ns/$name',
  getParentRoute: () => rootRouteImport,
} as any)
const CNsNameEditRoute = CNsNameEditRouteImport.update({
  id: '/c/$ns/$name_/edit',
  path: '/c/$ns/$name/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const CNsNameContributionsIndexRoute =
  CNsNameContributionsIndexRouteImport.update({
    id: '/c/$ns/$name_/contributions/',
    path: '/c/$ns/$name/contributions/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CNsNameContributionsNumberRoute =
  CNsNameContributionsNumberRouteImport.update({
    id: '/c/$ns/$name_/contributions/$number',
    path: '/c/$ns/$name/contributions/$number',
    getParentRoute: () => rootRouteImport,
  } as any)
const CNsNameContributionsNewRoute = CNsNameContributionsNewRouteImport.update({
  id: '/c/$ns/$name_/contributions/new',
  path: '/c/$ns/$name/contributions/new',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/me': typeof MeRoute
  '/settings': typeof SettingsRoute
  '/create/import': typeof CreateImportRoute
  '/guest/verify': typeof GuestVerifyRoute
  '/playground/diff': typeof PlaygroundDiffRoute
  '/create/': typeof CreateIndexRoute
  '/playground/': typeof PlaygroundIndexRoute
  '/c/$ns/$name': typeof CNsNameRoute
  '/c/$ns/$name/edit': typeof CNsNameEditRoute
  '/c/$ns/$name/contributions/$number': typeof CNsNameContributionsNumberRoute
  '/c/$ns/$name/contributions/new': typeof CNsNameContributionsNewRoute
  '/c/$ns/$name/contributions/': typeof CNsNameContributionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/me': typeof MeRoute
  '/settings': typeof SettingsRoute
  '/create/import': typeof CreateImportRoute
  '/guest/verify': typeof GuestVerifyRoute
  '/playground/diff': typeof PlaygroundDiffRoute
  '/create': typeof CreateIndexRoute
  '/playground': typeof PlaygroundIndexRoute
  '/c/$ns/$name': typeof CNsNameRoute
  '/c/$ns/$name/edit': typeof CNsNameEditRoute
  '/c/$ns/$name/contributions/$number': typeof CNsNameContributionsNumberRoute
  '/c/$ns/$name/contributions/new': typeof CNsNameContributionsNewRoute
  '/c/$ns/$name/contributions': typeof CNsNameContributionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/me': typeof MeRoute
  '/settings': typeof SettingsRoute
  '/create/import': typeof CreateImportRoute
  '/guest/verify': typeof GuestVerifyRoute
  '/playground/diff': typeof PlaygroundDiffRoute
  '/create/': typeof CreateIndexRoute
  '/playground/': typeof PlaygroundIndexRoute
  '/c/$ns/$name': typeof CNsNameRoute
  '/c/$ns/$name_/edit': typeof CNsNameEditRoute
  '/c/$ns/$name_/contributions/$number': typeof CNsNameContributionsNumberRoute
  '/c/$ns/$name_/contributions/new': typeof CNsNameContributionsNewRoute
  '/c/$ns/$name_/contributions/': typeof CNsNameContributionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/browse'
    | '/me'
    | '/settings'
    | '/create/import'
    | '/guest/verify'
    | '/playground/diff'
    | '/create/'
    | '/playground/'
    | '/c/$ns/$name'
    | '/c/$ns/$name/edit'
    | '/c/$ns/$name/contributions/$number'
    | '/c/$ns/$name/contributions/new'
    | '/c/$ns/$name/contributions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/browse'
    | '/me'
    | '/settings'
    | '/create/import'
    | '/guest/verify'
    | '/playground/diff'
    | '/create'
    | '/playground'
    | '/c/$ns/$name'
    | '/c/$ns/$name/edit'
    | '/c/$ns/$name/contributions/$number'
    | '/c/$ns/$name/contributions/new'
    | '/c/$ns/$name/contributions'
  id:
    | '__root__'
    | '/'
    | '/browse'
    | '/me'
    | '/settings'
    | '/create/import'
    | '/guest/verify'
    | '/playground/diff'
    | '/create/'
    | '/playground/'
    | '/c/$ns/$name'
    | '/c/$ns/$name_/edit'
    | '/c/$ns/$name_/contributions/$number'
    | '/c/$ns/$name_/contributions/new'
    | '/c/$ns/$name_/contributions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrowseRoute: typeof BrowseRoute
  MeRoute: typeof MeRoute
  SettingsRoute: typeof SettingsRoute
  CreateImportRoute: typeof CreateImportRoute
  GuestVerifyRoute: typeof GuestVerifyRoute
  PlaygroundDiffRoute: typeof PlaygroundDiffRoute
  CreateIndexRoute: typeof CreateIndexRoute
  PlaygroundIndexRoute: typeof PlaygroundIndexRoute
  CNsNameRoute: typeof CNsNameRoute
  CNsNameEditRoute: typeof CNsNameEditRoute
  CNsNameContributionsNumberRoute: typeof CNsNameContributionsNumberRoute
  CNsNameContributionsNewRoute: typeof CNsNameContributionsNewRoute
  CNsNameContributionsIndexRoute: typeof CNsNameContributionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/': {
      id: '/create/'
      path: '/create'
      fullPath: '/create/'
      preLoaderRoute: typeof CreateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/import': {
      id: '/create/import'
      path: '/create/import'
      fullPath: '/create/import'
      preLoaderRoute: typeof CreateImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guest/verify': {
      id: '/guest/verify'
      path: '/guest/verify'
      fullPath: '/guest/verify'
      preLoaderRoute: typeof GuestVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground/': {
      id: '/playground/'
      path: '/playground'
      fullPath: '/playground/'
      preLoaderRoute: typeof PlaygroundIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground/diff': {
      id: '/playground/diff'
      path: '/playground/diff'
      fullPath: '/playground/diff'
      preLoaderRoute: typeof PlaygroundDiffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$ns/$name': {
      id: '/c/$ns/$name'
      path: '/c/$ns/$name'
      fullPath: '/c/$ns/$name'
      preLoaderRoute: typeof CNsNameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$ns/$name_/edit': {
      id: '/c/$ns/$name_/edit'
      path: '/c/$ns/$name/edit'
      fullPath: '/c/$ns/$name/edit'
      preLoaderRoute: typeof CNsNameEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$ns/$name_/contributions/': {
      id: '/c/$ns/$name_/contributions/'
      path: '/c/$ns/$name/contributions'
      fullPath: '/c/$ns/$name/contributions/'
      preLoaderRoute: typeof CNsNameContributionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$ns/$name_/contributions/$number': {
      id: '/c/$ns/$name_/contributions/$number'
      path: '/c/$ns/$name/contributions/$number'
      fullPath: '/c/$ns/$name/contributions/$number'
      preLoaderRoute: typeof CNsNameContributionsNumberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$ns/$name_/contributions/new': {
      id: '/c/$ns/$name_/contributions/new'
      path: '/c/$ns/$name/contributions/new'
      fullPath: '/c/$ns/$name/contributions/new'
      preLoaderRoute: typeof CNsNameContributionsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrowseRoute: BrowseRoute,
  MeRoute: MeRoute,
  SettingsRoute: SettingsRoute,
  CreateImportRoute: CreateImportRoute,
  GuestVerifyRoute: GuestVerifyRoute,
  PlaygroundDiffRoute: PlaygroundDiffRoute,
  CreateIndexRoute: CreateIndexRoute,
  PlaygroundIndexRoute: PlaygroundIndexRoute,
  CNsNameRoute: CNsNameRoute,
  CNsNameEditRoute: CNsNameEditRoute,
  CNsNameContributionsNumberRoute: CNsNameContributionsNumberRoute,
  CNsNameContributionsNewRoute: CNsNameContributionsNewRoute,
  CNsNameContributionsIndexRoute: CNsNameContributionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
