/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BrowseRouteImport } from './routes/browse'
import { Route as CreateRouteImport } from './routes/create'
import { Route as PlaygroundIndexRouteImport } from './routes/playground.index'
import { Route as PlaygroundDiffRouteImport } from './routes/playground.diff'
import { Route as CNsNameRouteImport } from './routes/c.$ns.$name'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseRoute = BrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundIndexRoute = PlaygroundIndexRouteImport.update({
  id: '/playground/',
  path: '/playground/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundDiffRoute = PlaygroundDiffRouteImport.update({
  id: '/playground/diff',
  path: '/playground/diff',
  getParentRoute: () => rootRouteImport,
} as any)
const CNsNameRoute = CNsNameRouteImport.update({
  id: '/c/$ns/$name',
  path: '/c/$ns/$name',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/create': typeof CreateRoute
  '/playground/diff': typeof PlaygroundDiffRoute
  '/playground/': typeof PlaygroundIndexRoute
  '/c/$ns/$name': typeof CNsNameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/create': typeof CreateRoute
  '/playground/diff': typeof PlaygroundDiffRoute
  '/playground': typeof PlaygroundIndexRoute
  '/c/$ns/$name': typeof CNsNameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/browse': typeof BrowseRoute
  '/create': typeof CreateRoute
  '/playground/diff': typeof PlaygroundDiffRoute
  '/playground/': typeof PlaygroundIndexRoute
  '/c/$ns/$name': typeof CNsNameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/browse'
    | '/create'
    | '/playground/diff'
    | '/playground/'
    | '/c/$ns/$name'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/browse'
    | '/create'
    | '/playground/diff'
    | '/playground'
    | '/c/$ns/$name'
  id:
    | '__root__'
    | '/'
    | '/browse'
    | '/create'
    | '/playground/diff'
    | '/playground/'
    | '/c/$ns/$name'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrowseRoute: typeof BrowseRoute
  CreateRoute: typeof CreateRoute
  PlaygroundDiffRoute: typeof PlaygroundDiffRoute
  PlaygroundIndexRoute: typeof PlaygroundIndexRoute
  CNsNameRoute: typeof CNsNameRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse': {
      id: '/browse'
      path: '/browse'
      fullPath: '/browse'
      preLoaderRoute: typeof BrowseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground/': {
      id: '/playground/'
      path: '/playground'
      fullPath: '/playground/'
      preLoaderRoute: typeof PlaygroundIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground/diff': {
      id: '/playground/diff'
      path: '/playground/diff'
      fullPath: '/playground/diff'
      preLoaderRoute: typeof PlaygroundDiffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$ns/$name': {
      id: '/c/$ns/$name'
      path: '/c/$ns/$name'
      fullPath: '/c/$ns/$name'
      preLoaderRoute: typeof CNsNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrowseRoute: BrowseRoute,
  CreateRoute: CreateRoute,
  PlaygroundDiffRoute: PlaygroundDiffRoute,
  PlaygroundIndexRoute: PlaygroundIndexRoute,
  CNsNameRoute: CNsNameRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
