/**
 * `pnpm conformance:review`
 *
 * 为人工审阅生成一份可读的摘要：每个用例的标题、审阅要点、draft 的关键内容（fragment 顺序与
 * 文本、参与者、late slot、汇总的 rating / license、错误码或发布结论），以及机器预检结果。
 * 输出写到 `spec/conformance/REVIEW.md`（不提交），审阅人对照规范逐条确认后再运行 accept。
 */
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { ContextIRSchema, displayFragmentId } from "@char-pub/core";
import type { CaseMeta } from "../runner/types.js";
import { CASES_DIR } from "./cases.js";
import { precheck } from "./precheck-lib.js";

const OUT = join(CASES_DIR, "..", "REVIEW.md");

function short(k: string): string {
  return k.length > 14 ? `${k.slice(0, 12)}…` : k;
}

function irSummary(text: string): string[] {
  const ir = ContextIRSchema.parse(JSON.parse(text));
  const lines: string[] = [];
  lines.push(
    `- root: \`${ir.root.ref}\` · effective rating **${ir.meta.rating}** · locales ${ir.meta.available_locales.join(", ")}`,
  );
  lines.push(
    `- rating sources: ${ir.meta.rating_sources.map((r) => `${r.ref}${r.asset ? `/${r.asset}` : ""}=${r.rating}`).join("; ")}`,
  );
  lines.push(
    `- licenses: ${ir.meta.licenses.map((l) => `${l.ref}${l.asset ? `/${l.asset}` : ""}=${l.license}`).join("; ")}`,
  );
  if (ir.meta.content_warnings.length)
    lines.push(`- content warnings: ${ir.meta.content_warnings.join(", ")}`);
  if (ir.meta.au) lines.push("- **AU**: an intrinsic dependency was force-overridden");
  lines.push("- fragments (in IR order):");
  for (const f of ir.fragments) {
    const text =
      f.content.type === "text"
        ? f.content.text
        : f.content.type === "dialogue"
          ? f.content.turns
              .map((t) => `${short(t.speaker.replace("participant:", ""))}: ${t.text}`)
              .join(" / ")
          : f.content.type;
    const via = f.origin.via.length ? ` via ${f.origin.via.join("→")}` : "";
    const over = f.origin.overridden_by?.length
      ? ` overridden(${f.origin.overridden_by.map((o) => o.op).join(",")})`
      : "";
    const act =
      f.activation.mode === "keyword"
        ? `keyword[${f.activation.keys.join("|")}]`
        : f.activation.mode;
    const vis =
      f.visibility.scope === "private"
        ? ` private→${f.visibility.to.map((t) => short(t.replace("participant:", ""))).join(",")}`
        : "";
    lines.push(
      `  - \`${displayFragmentId(f.id)}\` ${f.kind} · ${act} · ${f.importance}${vis}${via}${over}${f.origin.stable ? "" : " · unstable"}`,
    );
    lines.push(`    > ${text.replaceAll("\n", " ").slice(0, 160)}`);
    for (const [loc, c] of Object.entries(f.locales ?? {})) {
      if (c.type === "text")
        lines.push(`    > [${loc}] ${c.text.replaceAll("\n", " ").slice(0, 160)}`);
    }
  }
  if (ir.graph.removed.length) {
    lines.push(
      `- removed: ${ir.graph.removed.map((r) => `${displayFragmentId(r.id)} (${r.by.reason})`).join(", ")}`,
    );
  }
  lines.push(
    `- participants: ${ir.participants.map((p) => `${short(p.key)}${p.ref ? `=${p.ref}` : ""}${p.late ? ` late:${short(p.late)}` : ""}`).join("; ")}`,
  );
  lines.push(
    `- late slots: ${ir.late_slots.map((s) => `${short(s.key)} accepts ${s.accepts.join("/")} ${s.required ? "required" : "optional"} used_by ${s.used_by.length}`).join("; ")}`,
  );
  if (ir.bootstrap.greetings.length) {
    lines.push(
      `- greetings: ${ir.bootstrap.greetings.map((g) => `${g.id}: “${g.text}”`).join("; ")}`,
    );
  }
  if (ir.assets.length) {
    lines.push(
      `- assets: ${ir.assets.map((a) => `${displayFragmentId(a.id)} ${a.role} ${a.access}${a.url ? " (url)" : ""}`).join("; ")}`,
    );
  }
  if (ir.diagnostics.length)
    lines.push(`- diagnostics: ${ir.diagnostics.map((d) => d.code).join(", ")}`);
  return lines;
}

const out: string[] = [
  "# Conformance review sheet",
  "",
  "Generated by `pnpm conformance:review`. Not committed. For each case, compare the draft with",
  "the specification and the case notes, then run `pnpm conformance:accept <case> --reviewer <name>`.",
  "",
];
for (const dir of readdirSync(CASES_DIR).sort()) {
  const meta = JSON.parse(readFileSync(join(CASES_DIR, dir, "case.json"), "utf8")) as CaseMeta;
  out.push(
    `## ${dir}`,
    "",
    `**${meta.title}** · kind \`${meta.kind}\` · status \`${meta.status}\``,
    "",
  );
  if (meta.notes) out.push(`Check: ${meta.notes}`, "");
  const draft = join(CASES_DIR, dir, "draft");
  if (existsSync(join(draft, "context-ir.json"))) {
    const text = readFileSync(join(draft, "context-ir.json"), "utf8");
    const issues = precheck(text);
    out.push(issues.length ? `Precheck: **FAIL** — ${issues.join("; ")}` : "Precheck: ok", "");
    out.push(...irSummary(text), "");
  } else if (existsSync(join(draft, "error.json"))) {
    out.push(`Result: error \`${readFileSync(join(draft, "error.json"), "utf8").trim()}\``, "");
  } else if (existsSync(join(draft, "publish.json"))) {
    out.push(`Result: publish \`${readFileSync(join(draft, "publish.json"), "utf8").trim()}\``, "");
  } else {
    out.push("Result: not wired yet (assembler / ccv3 implementation pending).", "");
  }
}
writeFileSync(OUT, `${out.join("\n")}\n`);
console.log(`wrote ${OUT}`);
